[project]
name = "poc-embeddings-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "chonkie>=1.4.0",
    "docling>=2.58.0",
]
